### ISSUE TITLE
Create Mock-ups for displaying OpenJS Foundation mark on project websites

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/artwork#4]
@kborchers had the great idea that we should provide a couple of examples for projects to pick from in choosing how to display the mark on project websites. 

The webhint team has a very small, [tasteful banner](https://webhint.io/) in their header, for example.

**Comment by jorydotcom** [comment]
I'm fine with that solution; I just think having some examples for inspo will be nice. 

So I don't lose this thread, is it OK if we keep the issue open until we get the new branding repo up per what's been discussed in openjs-foundation/cross-project-council#280 ? we can transfer this issue over there then.

**Comment by joesepi** [comment]
Sorry, I closed prematurely. Per @jorydotcom's comment (https://github.com/openjs-foundation/artwork/issues/4#issuecomment-525328997) I transferred it to this artwork repo. Thanks!

**Comment by brianwarner** [comment]
Doing some issue cleanup, with the [recommended project footer](https://github.com/openjs-foundation/artwork#copyright-notices-for-project-website-footers) having been on the artwork repo for quite some time, I think this can be resolved.
