### ISSUE TITLE
Artwork missing for some projects

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/artwork#6]
Just glancing at the project directories, I see a few projects may be missing:
- nvm
- fastify
- amp
- electron

Perhaps just the new projects?

We may need to include this step in graduating or even joining incubation/onboarding checklist?

**Comment by ljharb** [comment]
nvm has no artwork to provide.

**Comment by Eomm** [comment]
> We may need to include this step in graduating or even joining incubation/onboarding checklist?

This would be useful: I followed the fastify process to be compliance with the checklist and I totally miss this repo/graphics tasks

(I'm quite ready to send a PR to add the fastify logos)

**Comment by brianwarner** [comment]
Doing some cleanup on old issues, it looks like we're set on this. I'll resolve the issue. Thanks all!
